version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: apidb
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: api-sample
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/apidb?authSource=admin
      OTEL_EXPORTER_OTLP_ENDPOINT: host.docker.internal:4317
      SERVICE_NAME: api-sample
      SERVICE_VERSION: 1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
